reversed variant for --map-passwd and --map-group
mpartel/bindfs pull request #113
Opened 2022-06-22 18:16 UTC by sshilovsky

--map-passwd-rev and --map-group-rev

My use case for --map-group-rev is mounting /dev into chroot tree with different UID/GID. The other one was added just for completeness

2022-06-23 04:55 UTC, mpartel requested changes
Nice!
Could you also add a test case to `tests/test_bindfs.rb`? You can copy the `root_testenv("--map-passwd=...` block as a starting point.

2022-06-23 04:55 UTC, mpartel commented on src/bindfs.c
> +        OPT_OFFSET2("--map-group-rev=%s", "map-group=%s", map_group_rev, -1),
```suggestion
        OPT_OFFSET2("--map-passwd-rev=%s", "map-passwd-rev=%s", map_passwd_rev, -1),
        OPT_OFFSET2("--map-group-rev=%s", "map-group-rev=%s", map_group_rev, -1),
```

2022-06-23 04:55 UTC, mpartel commented on src/bindfs.c
> +           " --map-group-rev=<groupfile>    Load reversed gid mapping from <groupfile>.\n"
Let's line these up :)
```suggestion
           " --map-passwd=...           Load uid mapping from passwd-like file.\n"
           " --map-group=...            Load gid mapping from group-like file.\n"
           " --map-passwd-rev=...       Load reversed uid mapping from  passwd-like file.\n"
           " --map-group-rev=...        Load reversed gid mapping from group-like file.\n"
```

2022-06-24 17:51 UTC, merged

2022-06-24 17:55 UTC, mpartel commented
Released as 1.16.1.
Thanks!

(I left out the change for skipping the test if unshare failed, because I'm uncomfortable with silently skipping tests if something goes wrong. It'd be better to change the test system so that a single failure doesn't block other tests from running, but I have too little time to work on bindfs these days.)

2022-06-24 20:23 UTC, sshilovsky commented
Thank you for prompt merge!

On `unshare`, it is a step in the process of initialization environment for that particular test. I think that it failing can only mean that the initialization is impossible here, so the test can be skipped, just like it's skipped currently based on parsing `man unshare`.

Although there is another possibility that my chroot, which I was running the tests inside, was set up wrong. I should look into that anyway.

2022-06-25 12:41 UTC, mpartel commented
Yeah, making the tests work in a variety of environments is a totally valid way to look at it (and some test frameworks explicitly support it), I just tend to put a lot more weight on dangers of invisible failures.